### ISSUE TITLE
Class 'String' has no instance method '<<'

### ISSUE THREAD

**Issue by Akshay-akkay** [Sipioteo/auto_localization#6]
Showing this error in console every time the package fuction runs.
```
E/flutter ( 4524): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method '<<'.
E/flutter ( 4524): Receiver: "406398"
E/flutter ( 4524): Tried calling: <<(3), stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 4524): #1      GoogleTokenGenerator.wr
package:translator/…/tokens/google_token_gen.dart:80
E/flutter ( 4524): #2      GoogleTokenGenerator.tokenGen
package:translator/…/tokens/google_token_gen.dart:58
E/flutter ( 4524): #3      GoogleTokenGenerator.generateToken
package:translator/…/tokens/google_token_gen.dart:14
E/flutter ( 4524): #4      GoogleTranslator.translate
package:translator/src/google_translator.dart:46
E/flutter ( 4524): #5      AutoLocalization._executeTranslate
package:auto_localization/auto_localization.dart:66
E/flutter ( 4524): <asynchronous suspension>
E/flutter ( 4524): #6      AutoLocalization.translate
package:auto_localization/auto_localization.dart:80
E/flutter ( 4524): <asynchronous suspension>
E/flutter ( 4524): #7      _TranslatedTextState.translateText
package:housy_pro/…/widgets/translatedText.dart:31
E/flutter ( 4524): <asynchronous suspension>
E/flutter ( 4524):
I/chatty  ( 4524): uid=10153(com.housypartner) 2.ui identical 1258 lines
```

**Comment by dhruvd0** [comment]
Seems like an issue in the google translator package: https://github.com/gabrielpacheco23/google-translator/issues/41

**Comment by davidgalarza** [comment]
Any update, I'm facing the same issue. I'm getting reports of this error on my Crashlytics account.
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: NoSuchMethodError: Class 'String' has no instance method '<<'.
Receiver: "406398"
Tried calling: <<(3). Error thrown null.
       at ._objectNoSuchMethod(.java)
       at GoogleTokenGenerator.wr(GoogleTokenGenerator.java:80)
       at GoogleTokenGenerator.tokenGen(GoogleTokenGenerator.java:58)
       at GoogleTokenGenerator.generateToken(GoogleTokenGenerator.java:14)
       at GoogleTranslator.translate(GoogleTranslator.java:46)
       at .translateWords(.java:35)
       at _DailyRevisionState._initLesson(_DailyRevisionState.java:206)
```

**Comment by Sipioteo** [comment]
I will check
